export const REQUIRED_FIELDS = [
  "fullName",
  "gender",
  "birthDate",
  "country",
  "city",
];

export const genderOptions = [
  { value: "female", label: "Female" },
  { value: "male", label: "Male" },
  { value: "non-binary", label: "Non-binary" },
  { value: "prefer_not_say", label: "Prefer not to say" },
];

export const countryCityOptions = [
  {
    value: "Vietnam",
    label: "Vietnam",
    cities: [
      "Can Tho",
      "Da Lat",
      "Da Nang",
      "Hai Phong",
      "Hanoi",
      "Ho Chi Minh City",
      "Hue",
      "Nam Dinh",
      "Nghe An",
      "Ninh Binh",
      "Quy Nhon",
      "Thanh Hoa",
      "Vinh",
      "Vung Tau",
    ],
  },
  {
    value: "Germany",
    label: "Germany",
    cities: [
      "Berlin",
      "Bonn",
      "Bremen",
      "Cologne",
      "Dresden",
      "Dusseldorf",
      "Frankfurt",
      "Hanover",
      "Hamburg",
      "Leipzig",
      "Munich",
      "Nuremberg",
      "Stuttgart",
      "Essen",
      "Dortmund",
      "Bochum",
      "Karlsruhe",
      "Aachen",
      "Freiburg",
      "Regensburg",
    ],
  },
  {
    value: "Japan",
    label: "Japan",
    cities: [
      "Fukuoka",
      "Hiroshima",
      "Kobe",
      "Kyoto",
      "Nagoya",
      "Osaka",
      "Sapporo",
      "Sendai",
      "Tokyo",
      "Yokohama",
    ],
  },
  {
    value: "Australia",
    label: "Australia",
    cities: [
      "Adelaide",
      "Brisbane",
      "Canberra",
      "Gold Coast",
      "Melbourne",
      "Perth",
      "Sydney",
    ],
  },
];

export const educationOptions = [
  "High school graduate",
  "University",
  "Vocational training",
  "Working professional",
];

export const hobbyOptions = [
  "Music & concerts",
  "Traveling",
  "Cooking & baking",
  "Video games",
  "Reading",
  "Fitness & gym",
  "Photography",
  "Art & design",
  "Movies & series",
  "Hiking & outdoors",
];

export const petOptions = ["Dog", "Cat", "Hamster", "Bird", "Fish"];

export const birthCountryOptions = [
  {
    value: "Vietnam",
    label: "Vietnam",
    cities: [
      "Hanoi",
      "Ho Chi Minh City",
      "Hai Phong",
      "Da Nang",
      "Can Tho",
      "Thua Thien Hue",
      "Khanh Hoa",
      "Binh Dinh",
      "Nghe An",
      "Dak Lak",
      "Lam Dong",
      "Dong Nai",
      "Binh Duong",
      "Quang Ninh",
      "Thanh Hoa",
      "Hai Duong",
      "Nam Dinh",
      "Thai Nguyen",
      "Phu Tho",
      "Kien Giang",
      "Bac Ninh",
      "Bac Giang",
      "Ha Nam",
      "Ninh Binh",
      "Ha Tinh",
      "Quang Binh",
      "Quang Tri",
      "Quang Ngai",
      "Binh Thuan",
      "An Giang",
    ],
  },
];
