import { useMemo } from "react";

export const FORTUNE_COOKIE_MESSAGES = [
  "Hãy gửi một lời chúc nho nhỏ cho ai đó bạn thương và tự thưởng cho mình một đĩa cơm tấm trứng ốp la giản dị mà ấm lòng.",
  "Dọn lại một góc bàn thật nhẹ nhàng rồi nấu bát canh bí đỏ thịt bằm để cảm giác bình yên tràn về.",
  "Nhắn hỏi thăm một người bạn đã lâu không trò chuyện và ngồi xuống thưởng tô hủ tiếu nước nóng để trái tim lắng lại.",
  "Mở cửa sổ cho gió ùa vào phòng, sau đó làm trứng chiên hành lá đơn giản như một cách tự ôm lấy mình.",
  "Hãy viết ra ba điều khiến bạn biết ơn hôm nay rồi ăn tô bún cá nóng hổi để vị ngọt nuôi dưỡng từng suy nghĩ.",
  "Đứng dậy vươn vai thật dài khi thấy căng thẳng, rồi pha chút trà gừng và ăn vài miếng khoai lang luộc cho cơ thể dịu xuống.",
  "Gửi một sticker đáng yêu cho người bạn thích, rồi nấu canh rau muống nấu tôm để bữa ăn tràn hương vị bình yên.",
  "Dành ít phút xem lại ảnh cũ và nấu đậu hũ rim mặn ngọt để căn bếp thơm như một lời an ủi ấm áp.",
  "Lau màn hình điện thoại và tự thưởng bánh mì trứng kẹp pate cho buổi xế đầy năng lượng dịu dàng.",
  "Hít sâu 30 giây trước khi trả lời tin nhắn và ăn chén cháo thịt bằm nóng để nhẹ bụng, nhẹ lòng.",
  "Bước ra ngoài vài phút để nhìn bầu trời rồi về làm tô mì tôm trộn đơn sơ nhưng đủ khiến bạn mỉm cười.",
  "Viết một câu động viên bản thân và nấu bầu xào tỏi để vị thanh giúp tâm trí thở ra nhẹ nhõm.",
  "Hãy hỏi thăm ai đó bạn yêu quý và kho cá kho tiêu để không gian bếp trở nên ấm như nhà.",
  "Gấp lại áo quần trên ghế và ăn bát canh chua cá để vị chua ngọt đánh thức nguồn năng lượng mới.",
  "Thiền một chút rồi làm rau muống xào tỏi cho cơ thể cảm nhận sự tươi mát đang trở về.",
  "Gửi một tấm ảnh dễ thương đến người khiến bạn vui và uống sữa đậu nành nóng với bánh tiêu mềm thơm.",
  "Viết ra điều khiến bạn rối lòng rồi ăn tô bún mọc để vị ngọt thanh đưa tâm trở lại yên ổn.",
  "Đặt lại giờ báo thức và kho nồi thịt trứng để căn bếp tỏa mùi thơm của sự chăm chút.",
  "Đổi hình nền thành thứ khiến bạn mỉm cười và làm chè đậu xanh đánh cho vị ngọt xoa dịu cả ngày.",
  "Dành 15 phút đọc sách và thưởng bát bánh canh giò heo để nạp năng lượng mới.",
  "Sắp xếp lại một góc nhỏ trong nhà và nấu cải thìa xào nấm để bữa ăn thêm xanh nhẹ.",
  "Gửi lời cảm ơn đến ai đã giúp bạn và ăn tô mì Quảng với chút đậu phộng giòn rụm.",
  "Viết lại một mục tiêu tuần này rồi làm bắp xào bơ để buổi chiều thơm lên một chút vui.",
  "Mở nhạc nhẹ khi thấy lòng nặng và nấu canh mướp nấu hẹ để hơi ấm lan khắp người.",
  "Hẹn gặp ai đó bạn nhớ và ăn cơm gạo lứt với gà luộc xé đầy lành mạnh.",
  "Rửa chiếc ly quen thuộc rồi uống nước sấu mát và ăn vài miếng ổi giòn cho tỉnh táo.",
  "Chia sẻ một điều tích cực và làm đĩa giá xào trứng mềm thơm như lời an ủi dễ thương.",
  "Gấp gọn mền gối rồi làm bánh mì bơ đường để gọi lại hương vị tuổi nhỏ.",
  "Hít sâu thật chậm rồi ăn bún riêu để vị thanh ngọt kéo tinh thần về lại đúng nhịp.",
  "Ghi một điều khiến bạn vui và xào mì bò cho buổi tối tròn vị.",
  "Xoay cổ thư giãn rồi uống nước chanh mật ong và ăn vài miếng trái cây mát lạnh.",
  "Mỉm cười với chính bạn trong gương và nấu canh gà lá giang để vị chua dịu nâng đỡ cảm xúc.",
  "Rửa bình nước yêu thích và ăn cơm trắng với cá chiên giòn cho buổi trưa thật thân quen.",
  "Kể cho ai đó một câu chuyện nhỏ rồi ăn bắp cải luộc chấm kho quẹt mộc mạc mà ngon lạ.",
  "Nghe lại playlist cũ và làm bánh chuối chiên giòn thơm như một buổi chiều dịu ngọt.",
  "Xem lại mục tiêu dài hạn rồi ăn tô bún bò Huế đậm đà để tiếp thêm quyết tâm.",
  "Hỏi thăm người thân đang làm gì và nấu cá thu sốt cà cho bữa tối nhẹ nhàng.",
  "Duỗi vai nhẹ ba lần rồi ăn vài cuốn gỏi cuốn chấm nước mắm chua ngọt.",
  "Gửi một emoji bất kỳ rồi uống trà atiso và nhâm nhi đậu phộng rang để lòng nhẹ hơn.",
  "Viết một lời nhắn hiền hòa và làm cơm chiên trứng thơm bơ cho bữa đơn giản.",
  "Cảm nhận không khí quanh mình rồi ăn tô mì gói nấu trứng như một niềm an ủi nhỏ.",
  "Xem một đoạn video dễ thương và nấu canh rau dền tôm khô tím ngọt cho buổi chiều mềm lại.",
  "Khen ai đó vì nỗ lực của họ rồi kho gà gừng cho bữa ăn ấm sực.",
  "Xoa nhẹ vai mình như một lời an ủi và ăn cháo trắng với trứng muối cho lòng mềm ra.",
  "Dọn dẹp với bài nhạc yêu thích rồi nấu đậu que xào thịt bằm cho một bữa thật gần gũi.",
  "Chọn một món đồ nhỏ để bỏ đi rồi uống nước dừa mát và ăn miếng bánh da lợn dẻo ngọt.",
  "Cảm ơn phiên bản hôm qua của bạn và nấu canh bầu nấu tôm để vị thanh thấm vào ngày mới.",
  "Cho phép bản thân nghỉ năm phút rồi ăn đĩa xôi đậu xanh thơm béo như một phần thưởng hiền hòa.",
  "Buông thư vài nhịp thở và thưởng chén chè trôi nước mềm ngọt như vòng tay êm dịu.",
  "Ghi lại một cảm nhận cuối ngày và nấu bát bánh canh chả cá để kết thúc ngày bằng sự ấm áp.",
];

export function useFortuneCookie() {
  return useMemo(() => FORTUNE_COOKIE_MESSAGES, []);
}

export default useFortuneCookie;
